#pragma once

namespace app::lua_bind {
    namespace AttackModule {
        u64 add_power(u64,int,float,bool) asm("_ZN3app8lua_bind28AttackModule__add_power_implEPNS_26BattleObjectModuleAccessorEifb") LINKABLE;
        u64 attack_data(u64,int,bool) asm("_ZN3app8lua_bind30AttackModule__attack_data_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        void clear(u64,int,bool) asm("_ZN3app8lua_bind24AttackModule__clear_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        void clear_all(u64) asm("_ZN3app8lua_bind28AttackModule__clear_all_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        void clear_inflict_kind_status(u64) asm("_ZN3app8lua_bind44AttackModule__clear_inflict_kind_status_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 enable_safe_pos(u64) asm("_ZN3app8lua_bind34AttackModule__enable_safe_pos_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_attacker_attribute(u64) asm("_ZN3app8lua_bind41AttackModule__get_attacker_attribute_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 get_offset2(u64,int,bool) asm("_ZN3app8lua_bind30AttackModule__get_offset2_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 get_power(u64,int,bool,float,bool) asm("_ZN3app8lua_bind28AttackModule__get_power_implEPNS_26BattleObjectModuleAccessorEibfb") LINKABLE;
        u64 get_power_up(u64) asm("_ZN3app8lua_bind31AttackModule__get_power_up_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 group(u64,int) asm("_ZN3app8lua_bind24AttackModule__group_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 hit_absolute(u64,int,uint,const Vector3f*,int,int) asm("_ZN3app8lua_bind31AttackModule__hit_absolute_implEPNS_26BattleObjectModuleAccessorEijRKN3phx8Vector3fEii") LINKABLE;
        u64 hit_absolute_joint(u64,int,uint,u64,int,int) asm("_ZN3app8lua_bind37AttackModule__hit_absolute_joint_implEPNS_26BattleObjectModuleAccessorEijN3phx6Hash40Eii") LINKABLE;
        u64 init_attack_pos(u64,int) asm("_ZN3app8lua_bind34AttackModule__init_attack_pos_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 is_attack(u64,int,bool) asm("_ZN3app8lua_bind28AttackModule__is_attack_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 is_attack_occur(u64) asm("_ZN3app8lua_bind34AttackModule__is_attack_occur_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 is_hit_abs(u64) asm("_ZN3app8lua_bind29AttackModule__is_hit_abs_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 is_infliction(u64,uint) asm("_ZN3app8lua_bind32AttackModule__is_infliction_implEPNS_26BattleObjectModuleAccessorEj") LINKABLE;
        u64 is_infliction_status(u64,uint) asm("_ZN3app8lua_bind39AttackModule__is_infliction_status_implEPNS_26BattleObjectModuleAccessorEj") LINKABLE;
        u64 off_target_kind(u64,int,uint) asm("_ZN3app8lua_bind34AttackModule__off_target_kind_implEPNS_26BattleObjectModuleAccessorEij") LINKABLE;
        u64 part_size(u64) asm("_ZN3app8lua_bind28AttackModule__part_size_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 power_mul_5th(u64) asm("_ZN3app8lua_bind32AttackModule__power_mul_5th_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 power_mul_status(u64) asm("_ZN3app8lua_bind35AttackModule__power_mul_status_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        // u64 set_absolute(u64,int,int,app::AttackAbsoluteData const&) asm("_ZN3app8lua_bind31AttackModule__set_absolute_implEPNS_26BattleObjectModuleAccessorEiiRKNS_18AttackAbsoluteDataE") LINKABLE;
        u64 set_accept_no_lr(u64,int,bool) asm("_ZN3app8lua_bind35AttackModule__set_accept_no_lr_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 set_add_reaction_frame(u64,int,float,bool) asm("_ZN3app8lua_bind41AttackModule__set_add_reaction_frame_implEPNS_26BattleObjectModuleAccessorEifb") LINKABLE;
        // u64 set_attack(u64,int,int,app::AttackData const&) asm("_ZN3app8lua_bind29AttackModule__set_attack_implEPNS_26BattleObjectModuleAccessorEiiRKNS_10AttackDataE") LINKABLE;
        u64 set_attack_2(u64,int,int) asm("_ZN3app8lua_bind31AttackModule__set_attack_2_implEPNS_26BattleObjectModuleAccessorEii") LINKABLE;
        u64 set_attack_composition_speed(u64,int,bool) asm("_ZN3app8lua_bind47AttackModule__set_attack_composition_speed_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 set_attack_height_all(u64,int attackHeight,bool) asm("_ZN3app8lua_bind40AttackModule__set_attack_height_all_implEPNS_26BattleObjectModuleAccessorENS_12AttackHeightEb") LINKABLE;
        u64 set_attack_keep_rumble(u64,int,bool) asm("_ZN3app8lua_bind41AttackModule__set_attack_keep_rumble_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 set_attack_level(u64,int,unsigned char) asm("_ZN3app8lua_bind35AttackModule__set_attack_level_implEPNS_26BattleObjectModuleAccessorEih") LINKABLE;
        u64 set_attack_reference_joint_id(u64,u64,int attackDirectionAxis1,int attackDirectionAxis2,int attackDirectionAxis3) asm("_ZN3app8lua_bind48AttackModule__set_attack_reference_joint_id_implEPNS_26BattleObjectModuleAccessorEN3phx6Hash40ENS_19AttackDirectionAxisES5_S5_") LINKABLE;
        u64 set_attack_scale(u64,float,bool) asm("_ZN3app8lua_bind35AttackModule__set_attack_scale_implEPNS_26BattleObjectModuleAccessorEfb") LINKABLE;
        // u64 set_attacker_attribute(u64,app::AttackerAttribute) asm("_ZN3app8lua_bind41AttackModule__set_attacker_attribute_implEPNS_26BattleObjectModuleAccessorENS_17AttackerAttributeE") LINKABLE;
        u64 set_base_offset(u64,const Vector2f*) asm("_ZN3app8lua_bind34AttackModule__set_base_offset_implEPNS_26BattleObjectModuleAccessorERKN3phx8Vector2fE") LINKABLE;
        u64 set_captured_same_time_attack(u64,int,bool) asm("_ZN3app8lua_bind48AttackModule__set_captured_same_time_attack_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 set_catch_only(u64,int,bool,bool) asm("_ZN3app8lua_bind33AttackModule__set_catch_only_implEPNS_26BattleObjectModuleAccessorEibb") LINKABLE;
        u64 set_catch_only_all(u64,bool,bool) asm("_ZN3app8lua_bind37AttackModule__set_catch_only_all_implEPNS_26BattleObjectModuleAccessorEbb") LINKABLE;
        u64 set_constraint_pos(u64,bool) asm("_ZN3app8lua_bind37AttackModule__set_constraint_pos_implEPNS_26BattleObjectModuleAccessorEb") LINKABLE;
        u64 set_critical_attack_damage_mul(u64,float) asm("_ZN3app8lua_bind49AttackModule__set_critical_attack_damage_mul_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_critical_attack_reaction_mul(u64,float) asm("_ZN3app8lua_bind51AttackModule__set_critical_attack_reaction_mul_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_customize_attack_ratio(u64,float) asm("_ZN3app8lua_bind45AttackModule__set_customize_attack_ratio_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_damage_effect_mul_scale(u64,float) asm("_ZN3app8lua_bind46AttackModule__set_damage_effect_mul_scale_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_damage_shake_scale(u64,float) asm("_ZN3app8lua_bind41AttackModule__set_damage_shake_scale_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_final_finish_cut_in(u64,int,bool,bool,float,bool) asm("_ZN3app8lua_bind42AttackModule__set_final_finish_cut_in_implEPNS_26BattleObjectModuleAccessorEibbfb") LINKABLE;
        u64 set_force_reaction(u64,int,bool,bool) asm("_ZN3app8lua_bind37AttackModule__set_force_reaction_implEPNS_26BattleObjectModuleAccessorEibb") LINKABLE;
        u64 set_ignore_just_shield(u64,bool) asm("_ZN3app8lua_bind41AttackModule__set_ignore_just_shield_implEPNS_26BattleObjectModuleAccessorEb") LINKABLE;
        u64 set_indirect_info(u64,uint,int,bool,bool) asm("_ZN3app8lua_bind36AttackModule__set_indirect_info_implEPNS_26BattleObjectModuleAccessorEjibb") LINKABLE;
        u64 set_ink_value(u64,int,float) asm("_ZN3app8lua_bind32AttackModule__set_ink_value_implEPNS_26BattleObjectModuleAccessorEif") LINKABLE;
        u64 set_invalid_invincible(u64,int,bool) asm("_ZN3app8lua_bind41AttackModule__set_invalid_invincible_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 set_invalid_xlu(u64,int,bool) asm("_ZN3app8lua_bind34AttackModule__set_invalid_xlu_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 set_is_critical_attack(u64,bool) asm("_ZN3app8lua_bind41AttackModule__set_is_critical_attack_implEPNS_26BattleObjectModuleAccessorEb") LINKABLE;
        u64 set_lerp(u64,int,int,int) asm("_ZN3app8lua_bind27AttackModule__set_lerp_implEPNS_26BattleObjectModuleAccessorEiii") LINKABLE;
        u64 set_lerp_ratio(u64,float,int) asm("_ZN3app8lua_bind33AttackModule__set_lerp_ratio_implEPNS_26BattleObjectModuleAccessorEfi") LINKABLE;
        u64 set_lr_check_back(u64,int) asm("_ZN3app8lua_bind36AttackModule__set_lr_check_back_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 set_lr_check_front(u64,int) asm("_ZN3app8lua_bind37AttackModule__set_lr_check_front_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 set_lr_check_front_lr(u64,int) asm("_ZN3app8lua_bind40AttackModule__set_lr_check_front_lr_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 set_nearest(u64,int,bool) asm("_ZN3app8lua_bind30AttackModule__set_nearest_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 set_no_damage_fly_smoke_all(u64,bool,bool) asm("_ZN3app8lua_bind46AttackModule__set_no_damage_fly_smoke_all_implEPNS_26BattleObjectModuleAccessorEbb") LINKABLE;
        u64 set_no_damage_orbit_all(u64,bool,bool) asm("_ZN3app8lua_bind42AttackModule__set_no_damage_orbit_all_implEPNS_26BattleObjectModuleAccessorEbb") LINKABLE;
        u64 set_no_dead_all(u64,bool,bool) asm("_ZN3app8lua_bind34AttackModule__set_no_dead_all_implEPNS_26BattleObjectModuleAccessorEbb") LINKABLE;
        u64 set_no_finish_camera(u64,int,bool,bool) asm("_ZN3app8lua_bind39AttackModule__set_no_finish_camera_implEPNS_26BattleObjectModuleAccessorEibb") LINKABLE;
        u64 set_no_hop_opponent_all(u64,bool,bool) asm("_ZN3app8lua_bind42AttackModule__set_no_hop_opponent_all_implEPNS_26BattleObjectModuleAccessorEbb") LINKABLE;
        u64 set_no_squat_damage_reaction_mul(u64,int,bool,bool) asm("_ZN3app8lua_bind51AttackModule__set_no_squat_damage_reaction_mul_implEPNS_26BattleObjectModuleAccessorEibb") LINKABLE;
        u64 set_no_team(u64,bool) asm("_ZN3app8lua_bind30AttackModule__set_no_team_implEPNS_26BattleObjectModuleAccessorEb") LINKABLE;
        u64 set_no_uniq_effect_all(u64,bool,bool) asm("_ZN3app8lua_bind41AttackModule__set_no_uniq_effect_all_implEPNS_26BattleObjectModuleAccessorEbb") LINKABLE;
        u64 set_no_world_scale(u64,bool) asm("_ZN3app8lua_bind37AttackModule__set_no_world_scale_implEPNS_26BattleObjectModuleAccessorEb") LINKABLE;
        u64 set_node(u64,int,u64) asm("_ZN3app8lua_bind27AttackModule__set_node_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40E") LINKABLE;
        u64 set_offset(u64,int,const Vector3f*) asm("_ZN3app8lua_bind29AttackModule__set_offset_implEPNS_26BattleObjectModuleAccessorEiRKN3phx8Vector3fE") LINKABLE;
        u64 set_offset2(u64,int,const Vector3f*) asm("_ZN3app8lua_bind30AttackModule__set_offset2_implEPNS_26BattleObjectModuleAccessorEiRKN3phx8Vector3fE") LINKABLE;
        u64 set_optional_hit_effect(u64,int,u64) asm("_ZN3app8lua_bind42AttackModule__set_optional_hit_effect_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40E") LINKABLE;
        u64 set_optional_hit_sound(u64,int,u64) asm("_ZN3app8lua_bind41AttackModule__set_optional_hit_sound_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40E") LINKABLE;
        u64 set_overlap_hit(u64,bool) asm("_ZN3app8lua_bind34AttackModule__set_overlap_hit_implEPNS_26BattleObjectModuleAccessorEb") LINKABLE;
        u64 set_poison_param(u64,int,int,int,float,bool) asm("_ZN3app8lua_bind35AttackModule__set_poison_param_implEPNS_26BattleObjectModuleAccessorEiiifb") LINKABLE;
        u64 set_power(u64,int,float,bool) asm("_ZN3app8lua_bind28AttackModule__set_power_implEPNS_26BattleObjectModuleAccessorEifb") LINKABLE;
        u64 set_power_add_status(u64,float) asm("_ZN3app8lua_bind39AttackModule__set_power_add_status_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_power_mul(u64,float) asm("_ZN3app8lua_bind32AttackModule__set_power_mul_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_power_mul_5th(u64,float) asm("_ZN3app8lua_bind36AttackModule__set_power_mul_5th_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_power_mul_status(u64,float) asm("_ZN3app8lua_bind39AttackModule__set_power_mul_status_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_power_speed_limit(u64,float) asm("_ZN3app8lua_bind40AttackModule__set_power_speed_limit_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_power_speed_status(u64,float) asm("_ZN3app8lua_bind41AttackModule__set_power_speed_status_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_power_up(u64,float) asm("_ZN3app8lua_bind31AttackModule__set_power_up_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_reaction_add(u64,int,int,bool) asm("_ZN3app8lua_bind35AttackModule__set_reaction_add_implEPNS_26BattleObjectModuleAccessorEiib") LINKABLE;
        u64 set_reaction_effect(u64,int,int,bool) asm("_ZN3app8lua_bind38AttackModule__set_reaction_effect_implEPNS_26BattleObjectModuleAccessorEiib") LINKABLE;
        u64 set_reaction_mul(u64,float) asm("_ZN3app8lua_bind35AttackModule__set_reaction_mul_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_reaction_mul_2nd(u64,float) asm("_ZN3app8lua_bind39AttackModule__set_reaction_mul_2nd_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_reaction_mul_3rd(u64,float) asm("_ZN3app8lua_bind39AttackModule__set_reaction_mul_3rd_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_reflect_attack(u64,bool) asm("_ZN3app8lua_bind37AttackModule__set_reflect_attack_implEPNS_26BattleObjectModuleAccessorEb") LINKABLE;
        u64 set_serial_hit_frame(u64,int,uint) asm("_ZN3app8lua_bind39AttackModule__set_serial_hit_frame_implEPNS_26BattleObjectModuleAccessorEij") LINKABLE;
        u64 set_set_off(u64,int,int attackSetOffKind) asm("_ZN3app8lua_bind30AttackModule__set_set_off_implEPNS_26BattleObjectModuleAccessorEiNS_16AttackSetOffKindE") LINKABLE;
        u64 set_shield_stiff_mul(u64,float) asm("_ZN3app8lua_bind39AttackModule__set_shield_stiff_mul_implEPNS_26BattleObjectModuleAccessorEf") LINKABLE;
        u64 set_size(u64,int,float) asm("_ZN3app8lua_bind27AttackModule__set_size_implEPNS_26BattleObjectModuleAccessorEif") LINKABLE;
        u64 set_special_paint(u64,int,int specialPaintKind) asm("_ZN3app8lua_bind36AttackModule__set_special_paint_implEPNS_26BattleObjectModuleAccessorEiNS_16SpecialPaintKindE") LINKABLE;
        u64 set_speed(u64,const Vector2f*) asm("_ZN3app8lua_bind28AttackModule__set_speed_implEPNS_26BattleObjectModuleAccessorERKN3phx8Vector2fE") LINKABLE;
        u64 set_target_category(u64,int,uint) asm("_ZN3app8lua_bind38AttackModule__set_target_category_implEPNS_26BattleObjectModuleAccessorEij") LINKABLE;
        u64 set_vec_target_pos(u64,int,u64,const Vector2f*,uint,bool) asm("_ZN3app8lua_bind37AttackModule__set_vec_target_pos_implEPNS_26BattleObjectModuleAccessorEiN3phx6Hash40ERKNS3_8Vector2fEjb") LINKABLE;
        u64 set_vector(u64,int,int,bool) asm("_ZN3app8lua_bind29AttackModule__set_vector_implEPNS_26BattleObjectModuleAccessorEiib") LINKABLE;
        u64 set_whole(u64,int,bool) asm("_ZN3app8lua_bind28AttackModule__set_whole_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
        u64 shield_stiff_mul(u64) asm("_ZN3app8lua_bind35AttackModule__shield_stiff_mul_implEPNS_26BattleObjectModuleAccessorE") LINKABLE;
        u64 size(u64,int) asm("_ZN3app8lua_bind23AttackModule__size_implEPNS_26BattleObjectModuleAccessorEi") LINKABLE;
        u64 sleep(u64,bool) asm("_ZN3app8lua_bind24AttackModule__sleep_implEPNS_26BattleObjectModuleAccessorEb") LINKABLE;
        u64 sleep_partialy(u64,int,bool) asm("_ZN3app8lua_bind33AttackModule__sleep_partialy_implEPNS_26BattleObjectModuleAccessorEib") LINKABLE;
    }
}