#include <switch.h>

#define StatusModule__change_status_request_from_script _ZN3app8lua_bind52StatusModule__change_status_request_from_script_implEPNS_26BattleObjectModuleAccessorEib
extern uint64_t  _ZN3app8lua_bind52StatusModule__change_status_request_from_script_implEPNS_26BattleObjectModuleAccessorEib(__int64_t, int, bool) LINKABLE;

#define StatusModule_status_kind _ZN3app8lua_bind30StatusModule__status_kind_implEPNS_26BattleObjectModuleAccessorE
extern int _ZN3app8lua_bind30StatusModule__status_kind_implEPNS_26BattleObjectModuleAccessorE(__int64_t) LINKABLE;

#define FighterInformation_is_operation_cpu _ZN3app8lua_bind41FighterInformation__is_operation_cpu_implEPNS_18FighterInformationE
extern bool _ZN3app8lua_bind41FighterInformation__is_operation_cpu_implEPNS_18FighterInformationE(__int64_t) LINKABLE;

#define WorkModule_get_int _ZN3app8lua_bind24WorkModule__get_int_implEPNS_26BattleObjectModuleAccessorEi
extern int _ZN3app8lua_bind24WorkModule__get_int_implEPNS_26BattleObjectModuleAccessorEi(__int64_t, int) LINKABLE;

#define FighterManager_get_fighter_information _ZN3app8lua_bind44FighterManager__get_fighter_information_implEPNS_14FighterManagerENS_14FighterEntryIDE
extern void* _ZN3app8lua_bind44FighterManager__get_fighter_information_implEPNS_14FighterManagerENS_14FighterEntryIDE(__int64_t, int) LINKABLE;

#define lib_lua_bind_get_value _ZN3lib18lua_bind_get_valueIiEEbmRT_
extern bool _ZN3lib18lua_bind_get_valueIiEEbmRT_(uint64_t, int*) LINKABLE;